version: '3.5'
volumes:
  pgsql: null
networks:
  location-net:
    driver: bridge
services:
  location.api:
    container_name: location-api
    image: location-api
    depends_on:
      - pgsql
      - seq
      - jaeger
    networks:
      - location-net
    build:
      context: .
      dockerfile: location.api/Dockerfile
    environment:
      - JAEGER_SERVICE_NAME=location.api
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      - SeqUrl=http://seq:5341
      - SEQ_ADDRESS=http://seq:5341
    ports:
      - '44338:80'
  pgsql:
    image: 'postgres:12'
    container_name: pgsql
    volumes:
      - 'pgsql:/var/lib/pgsql/data'
    networks:
      - location-net
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Temporal1
      POSTGRES_DB: postgres
  seq:
    container_name: seq
    image: 'datalust/seq:latest'
    volumes:
      - '/datadrive:/data'
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
    networks:
      - location-net
    ports:
      - '5341:80'
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
    networks:
      - location-net